### ISSUE TITLE
Nanban is spelled incorrectly 

### ISSUE THREAD

**Issue by mugunth** [thamizha/thamizha-solthiruthi#2]
நண்பன் is the correct . But our spell checker shows நன்பன் as correct spelling.

**Comment by neotamizhan** [comment]
முகுந்த்,

dic கோப்புல நன்பன் அப்படிங்கற சொல் இருக்கு... அதனால தான் அது சரியான
சொல்லுன்னு காட்டுது.

On Thu, Dec 22, 2011 at 7:33 AM, Mugunth <
reply@reply.github.com

> wrote:
> 
> நண்பன் is the correct . But our spell checker shows நன்பன் as correct
> spelling.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thamizha/solthiruthi/issues/2

## 

---

http://angumingum.wordpress.com

**Comment by mugunth** [comment]
அப்போ dic கோப்புல இருக்கற தவறான  'நன்பன்' என்ற  சொல்ல மாத்திடுங்க.

**Comment by lavanyasundararajan** [comment]
Hi Mugunth,

 Ok I will check out and correct it

Anbudan,
Lavanya

On Thu, Dec 22, 2011 at 10:03 AM, Mugunth <
reply@reply.github.com

**Comment by mugunth** [comment]
I have corrected this in .dic file. It should solve this issue.

**Comment by lavanyasundararajan** [comment]
Thanks Muguth,

  I was in official tour till today. I will discuss further tomorrow. Can
you come online voice call sometime tomorrow.
Thanks,
Lavanya

On Fri, Jan 6, 2012 at 4:28 AM, Mugunth <
reply@reply.github.com

**Comment by mugunth** [comment]
Sure,
I will be online in skype most of the time. You can ping me when u find me
online.

Regards,
Mugunth

On Sat, Jan 7, 2012 at 2:32 AM, lavanyas <
reply@reply.github.com

> wrote:
> 
> Thanks Muguth,
> 
>  I was in official tour till today. I will discuss further tomorrow. Can
> you come online voice call sometime tomorrow.
> Thanks,
> Lavanya
> 
> On Fri, Jan 6, 2012 at 4:28 AM, Mugunth <
> reply@reply.github.com
> 
> > wrote:
> > 
> > I have corrected this in .dic file. It should solve this issue.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/thamizha/solthiruthi/issues/2#issuecomment-3377951
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thamizha/solthiruthi/issues/2#issuecomment-3386859

## 

Blog: http://mugunth.blogspot.com
Follow me @ http://twitter.com/mugunth
